// BibleBooksFull.swift
import Foundation

// Full 66-book table of contents for KJV.
// Abbreviations help the parser accept inputs like "Ps 23", "1 Cor 13", etc.
let KJV_ALL_BOOKS: [BibleBook] = [
    .init(id: 1,  name: "Genesis",        abbreviations: ["Gen","Ge","Gn"],                chapters: 50),
    .init(id: 2,  name: "Exodus",         abbreviations: ["Exod","Ex"],                    chapters: 40),
    .init(id: 3,  name: "Leviticus",      abbreviations: ["Lev","Lv"],                     chapters: 27),
    .init(id: 4,  name: "Numbers",        abbreviations: ["Num","Nm","Nb"],                chapters: 36),
    .init(id: 5,  name: "Deuteronomy",    abbreviations: ["Deut","Dt"],                    chapters: 34),
    .init(id: 6,  name: "Joshua",         abbreviations: ["Josh","Jos"],                   chapters: 24),
    .init(id: 7,  name: "Judges",         abbreviations: ["Judg","Jdg","Jg"],              chapters: 21),
    .init(id: 8,  name: "Ruth",           abbreviations: ["Rth","Ru"],                     chapters: 4),
    .init(id: 9,  name: "1 Samuel",       abbreviations: ["1Sam","1Sa","1 Sm","1Samuel"],  chapters: 31),
    .init(id:10,  name: "2 Samuel",       abbreviations: ["2Sam","2Sa","2 Sm","2Samuel"],  chapters: 24),
    .init(id:11,  name: "1 Kings",        abbreviations: ["1Kgs","1Ki","1Kings"],          chapters: 22),
    .init(id:12,  name: "2 Kings",        abbreviations: ["2Kgs","2Ki","2Kings"],          chapters: 25),
    .init(id:13,  name: "1 Chronicles",   abbreviations: ["1Chr","1Ch","1Chron"],          chapters: 29),
    .init(id:14,  name: "2 Chronicles",   abbreviations: ["2Chr","2Ch","2Chron"],          chapters: 36),
    .init(id:15,  name: "Ezra",           abbreviations: ["Ezr"],                           chapters: 10),
    .init(id:16,  name: "Nehemiah",       abbreviations: ["Neh","Ne"],                     chapters: 13),
    .init(id:17,  name: "Esther",         abbreviations: ["Est","Es"],                     chapters: 10),
    .init(id:18,  name: "Job",            abbreviations: ["Job","Jb"],                     chapters: 42),
    .init(id:19,  name: "Psalms",         abbreviations: ["Ps","Psa","Pss","Psalm"],       chapters: 150),
    .init(id:20,  name: "Proverbs",       abbreviations: ["Prov","Pr"],                    chapters: 31),
    .init(id:21,  name: "Ecclesiastes",   abbreviations: ["Eccl","Ec"],                    chapters: 12),
    .init(id:22,  name: "Song of Solomon",abbreviations: ["Song","SoS","Cant","SongofSolomon"], chapters: 8),
    .init(id:23,  name: "Isaiah",         abbreviations: ["Isa","Is"],                     chapters: 66),
    .init(id:24,  name: "Jeremiah",       abbreviations: ["Jer","Je","Jr"],                chapters: 52),
    .init(id:25,  name: "Lamentations",   abbreviations: ["Lam","La"],                     chapters: 5),
    .init(id:26,  name: "Ezekiel",        abbreviations: ["Ezek","Eze","Ez"],              chapters: 48),
    .init(id:27,  name: "Daniel",         abbreviations: ["Dan","Da","Dn"],                chapters: 12),
    .init(id:28,  name: "Hosea",          abbreviations: ["Hos","Ho"],                     chapters: 14),
    .init(id:29,  name: "Joel",           abbreviations: ["Joel","Jl"],                    chapters: 3),
    .init(id:30,  name: "Amos",           abbreviations: ["Am"],                            chapters: 9),
    .init(id:31,  name: "Obadiah",        abbreviations: ["Obad","Ob"],                    chapters: 1),
    .init(id:32,  name: "Jonah",          abbreviations: ["Jon"],                           chapters: 4),
    .init(id:33,  name: "Micah",          abbreviations: ["Mic","Mi"],                     chapters: 7),
    .init(id:34,  name: "Nahum",          abbreviations: ["Nah","Na"],                     chapters: 3),
    .init(id:35,  name: "Habakkuk",       abbreviations: ["Hab","Hb"],                     chapters: 3),
    .init(id:36,  name: "Zephaniah",      abbreviations: ["Zeph","Zep","Zp"],              chapters: 3),
    .init(id:37,  name: "Haggai",         abbreviations: ["Hag","Hg"],                     chapters: 2),
    .init(id:38,  name: "Zechariah",      abbreviations: ["Zech","Zec","Zc"],              chapters: 14),
    .init(id:39,  name: "Malachi",        abbreviations: ["Mal","Ml"],                     chapters: 4),
    .init(id:40,  name: "Matthew",        abbreviations: ["Matt","Mt","Mat"],              chapters: 28),
    .init(id:41,  name: "Mark",           abbreviations: ["Mk","Mrk","Mar"],               chapters: 16),
    .init(id:42,  name: "Luke",           abbreviations: ["Lk","Luk"],                     chapters: 24),
    .init(id:43,  name: "John",           abbreviations: ["Jn","Jhn","Joh"],               chapters: 21),
    .init(id:44,  name: "Acts",           abbreviations: ["Acts","Ac"],                    chapters: 28),
    .init(id:45,  name: "Romans",         abbreviations: ["Rom","Ro","Rm"],                chapters: 16),
    .init(id:46,  name: "1 Corinthians",  abbreviations: ["1Cor","1Co","1Corinthians"],    chapters: 16),
    .init(id:47,  name: "2 Corinthians",  abbreviations: ["2Cor","2Co","2Corinthians"],    chapters: 13),
    .init(id:48,  name: "Galatians",      abbreviations: ["Gal","Ga"],                     chapters: 6),
    .init(id:49,  name: "Ephesians",      abbreviations: ["Eph","Ep"],                     chapters: 6),
    .init(id:50,  name: "Philippians",    abbreviations: ["Phil","Php","Pp"],              chapters: 4),
    .init(id:51,  name: "Colossians",     abbreviations: ["Col","Co"],                     chapters: 4),
    .init(id:52,  name: "1 Thessalonians",abbreviations: ["1Thess","1Th","1Thes"],         chapters: 5),
    .init(id:53,  name: "2 Thessalonians",abbreviations: ["2Thess","2Th","2Thes"],         chapters: 3),
    .init(id:54,  name: "1 Timothy",      abbreviations: ["1Tim","1Ti"],                   chapters: 6),
    .init(id:55,  name: "2 Timothy",      abbreviations: ["2Tim","2Ti"],                   chapters: 4),
    .init(id:56,  name: "Titus",          abbreviations: ["Titus","Tit"],                  chapters: 3),
    .init(id:57,  name: "Philemon",       abbreviations: ["Philem","Phm"],                 chapters: 1),
    .init(id:58,  name: "Hebrews",        abbreviations: ["Heb"],                          chapters: 13),
    .init(id:59,  name: "James",          abbreviations: ["Jas","Jam","Jm"],               chapters: 5),
    .init(id:60,  name: "1 Peter",        abbreviations: ["1Pet","1Pe","1Pt"],             chapters: 5),
    .init(id:61,  name: "2 Peter",        abbreviations: ["2Pet","2Pe","2Pt"],             chapters: 3),
    .init(id:62,  name: "1 John",         abbreviations: ["1John","1Jn","1Jhn"],           chapters: 5),
    .init(id:63,  name: "2 John",         abbreviations: ["2John","2Jn","2Jhn"],           chapters: 1),
    .init(id:64,  name: "3 John",         abbreviations: ["3John","3Jn","3Jhn"],           chapters: 1),
    .init(id:65,  name: "Jude",           abbreviations: ["Jude","Jud"],                   chapters: 1),
    .init(id:66,  name: "Revelation",     abbreviations: ["Rev","Re","Rv","Apoc"],         chapters: 22)
]
